// Generated by tools/design_mic_am_decimator.py --write-header.
// 24 ksps, pass 0..3 kHz, stop 6..12 kHz, 35 taps, unity DC.
#ifndef DSP_AM_DECIMATE_TAPS_HPP
#define DSP_AM_DECIMATE_TAPS_HPP
#include <array>
namespace dsp {
namespace am {
constexpr std::array<float, 35> decimate_taps{{
    3.247561108e-04f,
    6.688864960e-05f,
    -1.167249866e-03f,
    -1.671086764e-03f,
    1.140860608e-03f,
    5.263066385e-03f,
    3.226983594e-03f,
    -7.402597461e-03f,
    -1.403451152e-02f,
    -5.172403180e-04f,
    2.512288094e-02f,
    2.643547952e-02f,
    -1.826103404e-02f,
    -6.775522232e-02f,
    -3.785380721e-02f,
    1.075665057e-01f,
    2.915489078e-01f,
    3.759328127e-01f,
    2.915489078e-01f,
    1.075665057e-01f,
    -3.785380721e-02f,
    -6.775522232e-02f,
    -1.826103404e-02f,
    2.643547952e-02f,
    2.512288094e-02f,
    -5.172403180e-04f,
    -1.403451152e-02f,
    -7.402597461e-03f,
    3.226983594e-03f,
    5.263066385e-03f,
    1.140860608e-03f,
    -1.671086764e-03f,
    -1.167249866e-03f,
    6.688864960e-05f,
    3.247561108e-04f,
}};
}
}  // namespace dsp
#endif
