// Generated by tools/design_mic_ssb_interp_x2.py --write-header.
// Seven-tap half-band: [outer, 0, inner, center, inner, 0, outer].
// 192 ksps, pass <=3 kHz, stop >=93 kHz; prototype gain 2.
#ifndef DSP_INTERPOLATE_X2_TAPS_HPP
#define DSP_INTERPOLATE_X2_TAPS_HPP
namespace dsp {
namespace interpolate {
constexpr float ssb_x2_outer = -6.295384467e-02f;
constexpr float ssb_x2_inner = 5.629527569e-01f;
constexpr float ssb_x2_center = 1.000002146e+00f;
}  // namespace interpolate
}  // namespace dsp
#endif
