// Generated by tools/design_mic_ssb_interp.py --write-header.
// 64-tap equiripple, fs=96k, pass <=3k, stop >=9k, equal weights.
// Float32 coefficients; prototype sum=8 (unity reconstructed amplitude).
// phases[p][r] = h[p + 8*r]. No per-phase renormalization.
#ifndef DSP_INTERPOLATE_X8_TAPS_HPP
#define DSP_INTERPOLATE_X8_TAPS_HPP
#include <array>
namespace dsp {
namespace interpolate {
constexpr std::array<std::array<float, 8>, 8> ssb_x8_phases{{
    // BEGIN COEFFICIENTS
    {{-3.094396088e-04f, 5.664623342e-03f, -1.976640895e-02f, 6.177496538e-02f, 9.880051017e-01f, -4.380666837e-02f, 1.125104632e-02f, -1.924273674e-03f}},
    {{-2.909886185e-03f, 1.574029401e-02f, -5.793647468e-02f, 1.988908947e-01f, 9.335103035e-01f, -1.135775298e-01f, 3.216532245e-02f, -6.517549977e-03f}},
    {{-4.242599942e-03f, 2.692965046e-02f, -9.786115587e-02f, 3.584946394e-01f, 8.305451870e-01f, -1.480258405e-01f, 4.237276688e-02f, -8.317511529e-03f}},
    {{-6.390217692e-03f, 3.701278940e-02f, -1.320423633e-01f, 5.275136232e-01f, 6.902936697e-01f, -1.517064869e-01f, 4.315611720e-02f, -7.986653596e-03f}},
    {{-7.986653596e-03f, 4.315611720e-02f, -1.517064869e-01f, 6.902936697e-01f, 5.275136232e-01f, -1.320423633e-01f, 3.701278940e-02f, -6.390217692e-03f}},
    {{-8.317511529e-03f, 4.237276688e-02f, -1.480258405e-01f, 8.305451870e-01f, 3.584946394e-01f, -9.786115587e-02f, 2.692965046e-02f, -4.242599942e-03f}},
    {{-6.517549977e-03f, 3.216532245e-02f, -1.135775298e-01f, 9.335103035e-01f, 1.988908947e-01f, -5.793647468e-02f, 1.574029401e-02f, -2.909886185e-03f}},
    {{-1.924273674e-03f, 1.125104632e-02f, -4.380666837e-02f, 9.880051017e-01f, 6.177496538e-02f, -1.976640895e-02f, 5.664623342e-03f, -3.094396088e-04f}},
    // END COEFFICIENTS
}};
}
}  // namespace dsp
#endif
