EPIRB - Maritime
EPIRB - Radio Call Sign
ELT - Aviation
Serial User Protocol
Test User Protocol
Orbitography Protocol
National User Protocol
2nd Generation Beacons
EPIRB - MMSI / Location
ELT-24-bit Address / Location
ELT Serial Location
ELT Serial Aircraft Location
EPIRB Serial Location
PLB Serial Location
Ship Security Location
Test Standard Location
ELT National Location
EPIRB National Location
PLB National Location
Test National Location
RLS Location Protocol
ELT(DT) Location Protocol
Spare
Unknown
# L. 25: additional data
ELTs/SN
ELTs/AC op & SN
FF EPIRBs/SN
ELTs+AC 24-bit ad.
NFF EPIRBs/SN
Not Used
PLBs/SN
# L. 33: long additinal data
MMSI=0x%08lX MID=%ld
24 bits AC ad.
C/S TA #=%ld
Op Design.=%c%c%c
Nati. data=%ld
# L. 39: emmergency
Other
Fire
Flooding
Collision
Grounding
Capsizing
Sinking
Disabled
Abandoning
# L. 49: other emmergency
Fire
Med.
Dis.
# L. 53: 
Undefined
No device
Other/no device
Other device
121.5 MHz
SART
