501:ADE:AdelieLand
201:ALB:Albania
202:AND:Andorra
203:AUT:Austria
204:AZC:Azores
205:BEL:Belgium
206:BLR:Belarus
207:BUL:Bulgaria
208:VAT:Vatican
209:CYP:Cyprus
210:CYP:Cyprus
211:GER:Germany
212:CYP:Cyprus
213:GOG:Georgia
214:MOL:Moldova
215:MAL:MALTA
216:ARM:Armenia
218:GER:Germany
219:DEN:Denmark
220:DEN:Denmark
224:SPA:Spain
225:SPA:Spain
226:FRA:France
227:FRA:France
228:FRA:France
229:MAL:Malta
230:FIN:Finland
231:FAR:Faro Isle
232:UKM:G Britain
233:UKM:G Britain
234:UKM:G Britain
235:UKM:G Britain
236:GIB:Gibraltar
237:GRE:Greece
238:CRT:Croatia
239:GRE:Greece
240:GRE:Greece
241:GRE:Greece
242:MOR:Morocco
243:HUN:Hungary
244:NET:Netherland
245:NET:Netherland
246:NET:Netherland
247:ITA:Italy
248:MAL:Malta
249:MAL:Malta
250:IRE:Ireland
251:ICE:Iceland
252:LIE:Liechten
253:LUX:Luxembourg
254:MON:Monaco
255:MAE:Madeira
256:MAL:Malta
257:NOR:Norway
258:NOR:Norway
259:NOR:Norway
261:POL:Poland
262:MNT:Montenegro
263:POR:Portugal
264:ROM:Romania
265:SWE:Sweden
266:SWE:Sweden
267:SLV:Slovakia
268:SAN:San Marino
269:SWT:Swiss
270:CZH:Czech Rep
271:TUR:Turkiye
272:UKR:Ukraine
273:RUS:Russia
274:MKD:North Mac
275:LAT:Latvia
276:EST:Estonia
277:LIT:Lithuania
278:SVN:Slovenia
279:SER:Serbia
301:ANA:Anguilla
303:ALA:Alaska
304:ANT:Antigua
305:ANT:Antigua
306:NEA:N Antilles
307:ARU:Aruba
308:BAA:Bahamas
309:BAA:Bahamas
310:BER:Bermuda
311:BAA:Bahamas
312:BEZ:Belize
314:BAR:Barbados
316:CAN:Canada
319:CAY:Cayman Is
321:COS:Costa Rica
323:CUB:Cuba
325:DOM:Dominica
327:DOR:Dominican
329:GUA:Guadeloupe
330:GRA:Grenada
331:GRN:Greenland
332:GUT:Guatemala
334:HON:Honduras
336:HAI:Haiti
338:USA:USA
339:JAM:Jamaica
341:SKN:St Kitts
343:SLU:St Lucia
345:MEX:Mexico
347:MTQ:Martinique
348:MOT:Montserrat
350:NIC:Nicaragua
351:PAN:Panama
352:PAN:Panama
353:PAN:Panama
354:PAN:Panama
355:PAN:Panama
356:PAN:Panama
357:PAN:Panama
358:PUE:PuertoRico
359:ELS:ElSalvador
361:SPI:St Pierre
362:TAT:Trinidad
364:TUK:Caicos Is
366:USA:USA
367:USA:USA
368:USA:USA
369:USA:USA
370:PAN:Panama
371:PAN:Panama
372:PAN:Panama
373:PAN:Panama
374:PAN:Panama
375:SVG:St Vincent
376:SVG:St Vincent
377:SVG:St Vincent
378:BVI:Virgin GB
379:USV:Virgin US
401:AFG:Afghan
403:SAU:Saudi
405:BAN:Bangladesh
408:BAH:Bahrain
410:BHU:Bhutan
412:CHN:China
413:CHN:China
414:CHN:CHINA
416:TAI:Taipei
417:SRI:Sri Lanka
419:IND:India
422:IRN:Iran
423:AZR:Azerbaijan
425:IRQ:Iraq
428:ISR:Israel
431:JPN:Japan
432:JPN:Japan
434:TKM:Turkmenist
436:KAZ:Kazakhstan
437:UZB:Uzbekistan
438:JOR:Jordan
440:KOR:Korea Sou
441:KOR:Korea Sou
443:PAA:Palestine
445:KDR:Korea Nor
447:KUW:Kuwait
450:LEB:Lebanon
451:KYR:Kyrgyzia
453:MAC:Macao
455:MAV:Maldives
457:MNG:Mongolia
459:NEP:Nepal
461:OMN:Oman
463:PAK:Pakistan
466:QAT:Qatar
468:SYR:Syria
470:UAE:UAE
471:UAE:UAE
472:TJK:TAJIKISTAN
473:YEM:Yemen
475:YEM:Yemen
477:HKG:Hong Kong
478:BOS:Bosniaherz
503:AUS:Australia
506:BUR:Burma
508:BRU:Brunei
510:MIC:Micronesia
511:PAL:Palau
512:NZL:NewZealand
514:CMB:Cambodia
515:CMB:Cambodia
516:CHR:Christmas
518:COO:Cook Isles
520:FIJ:Fiji
523:COC:Cocos Isle
525:INO:Indonesia
529:KIR:Kiribati
531:LAO:Lao
533:MLY:Malaysia
536:MAI:Mariana Is
538:MAR:Marshall I
540:NCA:Caledonia
542:NIU:Niue Isle
544:NAU:Nauru
546:PLY:Polynesia
548:PHI:Philippine
550:TIM:TimorLeste
553:PAP:Papua NG
555:PIT:Pitcairn I
557:SOL:Solomon Is
559:ASA:Samoa USA
561:WSA:West Samoa
563:SIN:Singapore
564:SIN:Singapore
565:SIN:Singapore
566:SIN:SINGAPORE
567:THA:Thailand
570:TON:Tonga
572:TUV:Tuvalu Is
574:VIE:Vietnam
576:VAN:Vanuatu
577:VAN:Vanuatu
578:WAL:Wallis Is
601:SAF:So Africa
603:ANG:Angola
605:ALG:Algeria
607:SPL:St Paul
608:ASC:Ascension
609:BUI:Burundi
610:BEN:Benin
611:BOT:Botswana
612:CAR:CenAfr Rep
613:CAM:Cameroon
615:CON:Congo
616:COM:Comoros
617:CAP:Cape Verde
618:CRP:Crozet
619:IVO:IvoryCoast
620:COM:Comoros
621:DJI:Djibouti
622:EGY:Egypt
624:ETH:Ethiopia
625:ERT:Eritrea
626:GAB:Gabon Rep
627:GHA:Ghana
629:GAM:Gambia
630:GUB:Guinea Bis
631:EQG:Eq Guinea
632:GUN:Guinea Rep
633:BUF:Burkina FS
634:KEN:Kenya
635:KER:Kerguelen
636:LIB:Liberia
637:LIB:Liberia
638:SSD:Southsudan
642:LBY:Libya
644:LES:Lesotho
645:MAU:Mauritius
647:MAD:Madagascar
649:MLI:Mali
650:MOZ:Mozambique
654:MAA:Mauritania
655:MAW:Malawi
656:NIG:Niger
657:NIA:Nigeria
659:NAM:Namibia
660:REU:Reunion
661:RWA:Rwanda
662:SUD:Sudan
663:SEN:Senegal
664:SEY:Seychelle
665:SHE:St Helena
666:SOM:Somali
667:SIL:Sierra Leo
668:SAO:Sao Tome
669:SWZ:Eswatini
670:CHA:Chad
671:TOG:Togo
672:TUN:Tunisia
674:TAN:Tanzania
675:UGA:Uganda
676:ZAI:Zaire
677:TAN:Tanzania
678:ZAM:Zambia
679:ZIM:Zimbabwe
701:ARG:Argentina
710:BRA:Brazil
720:BOL:Bolivia
725:CHI:Chile
730:COL:Colombia
735:ECU:Ecuador
740:FAL:Falkland I
745:GUI:Guiana
750:GUY:Guyana
755:PAR:Paraguay
760:PER:Peru
765:SUR:Suriname
770:URU:Uruguay
775:VEN:Venezuela
