EPIRB - Maritime
EPIRB - Radio Call Sign
ELT - Aviation
Serial User Protocol
Test User Protocol
Orbitography Protocol
National User Protocol
2nd Generation Beacons
EPIRB - MMSI / Location
ELT-24-bit Address / Location
ELT Serial Location
ELT Serial Aircradt Location
EPIRB Serial Location
PLB Serial Location
Ship Security Location
Test Standard Location
ELT National Location
EPIRB National Location
PLB National Location
Test National Location
RLS Location Protocol
ELT(DT) Location Protocol
Spare