#!/usr/bin/env python3
"""Design/verify the Mic SSB x8 prototype (host-only scipy/numpy).

Default: verify the checked-in float32 coefficients, without writing files.
--write-header explicitly regenerates the coefficient header.
"""
import argparse
from pathlib import Path
import re
import numpy as np
import scipy
from scipy.signal import remez, freqz

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / 'firmware/baseband/dsp_interpolate_x8_taps.hpp'

def design():
    taps = remez(64, [0, 3000, 9000, 48000], [1, 0], weight=[1, 1],
                 fs=96000, maxiter=100, grid_density=32)
    return (taps * (8.0 / taps.sum())).astype(np.float32)

def read_taps():
    text = HEADER.read_text().split('// BEGIN COEFFICIENTS')[1].split('// END COEFFICIENTS')[0]
    values = [float(x) for x in re.findall(r'([-+]?\d+\.\d+e[-+]\d+)f', text)]
    assert len(values) == 64
    return np.array(values, dtype=np.float32).reshape(8,8).T.reshape(64)

def metrics(taps):
    f, h = freqz(taps.astype(float)/8, worN=1048576, fs=96000)
    a = abs(h); pb = a[f <= 3000]; sb = a[f >= 9000]
    result = dict(ripple_db=float(20*np.log10(pb.max()/pb.min())),
                  stopband_db=float(20*np.log10(sb.max())),
                  dc_gain=float(sum(taps.astype(float))/8),
                  phase_dc_sums=[float(sum(taps[p::8].astype(float))) for p in range(8)])
    assert result['ripple_db'] < .01
    assert result['stopband_db'] < -60
    assert abs(result['dc_gain']-1) < 1e-6
    return result

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write-header', action='store_true')
    args = parser.parse_args()
    taps = design()
    if args.write_header:
        rows = ['    {{' + ', '.join(f'{float(v):.9e}f' for v in taps[p::8]) + '}},' for p in range(8)]
        HEADER.write_text('''// Generated by tools/design_mic_ssb_interp.py --write-header.
// 64-tap equiripple, fs=96k, pass <=3k, stop >=9k, equal weights.
// Float32 coefficients; prototype sum=8 (unity reconstructed amplitude).
// phases[p][r] = h[p + 8*r]. No per-phase renormalization.
#ifndef DSP_INTERPOLATE_X8_TAPS_HPP
#define DSP_INTERPOLATE_X8_TAPS_HPP
#include <array>
namespace dsp { namespace interpolate {
constexpr std::array<std::array<float, 8>, 8> ssb_x8_phases{{
// BEGIN COEFFICIENTS
'''+'\n'.join(rows)+'''
// END COEFFICIENTS
}};
}}  // namespace dsp::interpolate
#endif
''')
    actual = read_taps()
    assert np.array_equal(actual, taps), 'Checked-in coefficients differ from this scipy design'
    print('numpy', np.__version__, 'scipy', scipy.__version__)
    print(metrics(actual))

if __name__ == '__main__': main()
