#!/usr/bin/env python3
"""Reproduce/verify the AM/DSB 24 -> 12 ksps FIR. Only --write-header writes."""
import argparse
from pathlib import Path
import re
import numpy as np
from scipy.signal import remez, freqz
ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / 'firmware/baseband/dsp_am_decimate_taps.hpp'
def design():
    h = remez(35, [0, 3000, 6000, 12000], [1, 0], fs=24000, grid_density=32)
    return (h / h.sum()).astype(np.float32)
def read_taps():
    return np.array(re.findall(r'([-+]?\d+\.\d+e[-+]\d+)f', HEADER.read_text()), dtype=np.float32)
def metrics(h):
    f, v = freqz(h.astype(float), worN=1048576, fs=24000)
    a = abs(v); p = a[f <= 3000]
    return dict(dc_gain=float(h.astype(float).sum()), ripple_db=float(20*np.log10(p.max()/p.min())), stopband_db=float(20*np.log10(a[f >= 6000].max())), delay_us=34/48000*1e6)
if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__); p.add_argument('--write-header', action='store_true'); args = p.parse_args()
    h = design()
    if args.write_header:
        HEADER.write_text('// Generated by tools/design_mic_am_decimator.py --write-header.\n// 24 ksps, pass 0..3 kHz, stop 6..12 kHz, 35 taps, unity DC.\n#ifndef DSP_AM_DECIMATE_TAPS_HPP\n#define DSP_AM_DECIMATE_TAPS_HPP\n#include <array>\nnamespace dsp { namespace am {\nconstexpr std::array<float, 35> decimate_taps{{\n' + '\n'.join('    '+f'{float(v):.9e}f,' for v in h) + '\n}};\n}}\n#endif\n')
    actual = read_taps(); assert np.array_equal(actual, h)
    result = metrics(actual); assert result['ripple_db'] < .0034 and result['stopband_db'] < -74
    print(result)
