#!/usr/bin/env python3
"""Host-only design and verification of the additional 96 -> 192 ksps stage.

Default is read-only. --write-header explicitly regenerates fixed coefficients.
"""
import argparse
from pathlib import Path
import re
import numpy as np
from scipy.signal import remez, freqz
from design_mic_ssb_interp import read_taps as read_x8

HEADER = Path(__file__).resolve().parents[1] / 'firmware/baseband/dsp_interpolate_x2_taps.hpp'

def design(n=7):
    h = remez(n, [0, 3000, 93000, 96000], [1, 0], weight=[1, 1],
              fs=192000, grid_density=32, maxiter=100)
    if n == 7:
        # Exact half-band zeros, rather than remez's ~1.5e-12 residues.
        h[1] = h[5] = 0
    return (2 * h / h.sum()).astype(np.float32)

def read_taps():
    values = re.findall(r'= ([-+]?\d+\.\d+e[-+]\d+)f;', HEADER.read_text())
    assert len(values) == 3
    a, b, c = np.array(values, dtype=np.float32)
    return np.array([a, 0, b, c, b, 0, a], dtype=np.float32)

def metrics(h):
    f = np.linspace(0, 96000, 1048577)
    a = abs(freqz(h.astype(float)/2, worN=2*np.pi*f/192000)[1])
    combined = a * abs(freqz(read_x8().astype(float)/8, worN=2*np.pi*f/96000)[1])
    def ripple(v):
        p = v[f <= 3000]
        return float(20*np.log10(p.max()/p.min()))
    return dict(ripple_db=ripple(a), stopband_db=float(20*np.log10(a[f >= 93000].max())),
                dc_gain=float(h.astype(float).sum()/2),
                combined_ripple_db=ripple(combined),
                combined_stopband_db=float(20*np.log10(combined[f >= 9000].max())))

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--write-header', action='store_true')
    p.add_argument('--survey', action='store_true', help='Compare 3..7 taps against the complete cascade')
    args = p.parse_args()
    h = design()
    if args.write_header:
        HEADER.write_text('''// Generated by tools/design_mic_ssb_interp_x2.py --write-header.
// Seven-tap half-band: [outer, 0, inner, center, inner, 0, outer].
// 192 ksps, pass <=3 kHz, stop >=93 kHz; prototype gain 2.
#ifndef DSP_INTERPOLATE_X2_TAPS_HPP
#define DSP_INTERPOLATE_X2_TAPS_HPP
namespace dsp {
namespace interpolate {
'''+''.join(f'constexpr float ssb_x2_{name} = {float(v):.9e}f;\n' for name,v in zip(['outer','inner','center'],h[[0,2,3]]))+'''}  // namespace interpolate
}  // namespace dsp
#endif
''')
    actual = read_taps()
    assert np.array_equal(actual, h)
    result = metrics(actual)
    assert result['ripple_db'] < .0001
    assert result['stopband_db'] < -100
    assert result['combined_ripple_db'] < .005
    assert result['combined_stopband_db'] < -70
    print('coefficients:', actual.tolist())
    print(result)
    if args.survey:
        for n in range(3, 8):
            print(n, metrics(design(n)))

if __name__ == '__main__':
    main()
