#pragma once
// DO NOT EDIT: IT IS AUTO GENERATED BY CMAKE!!!!

// clang-format off
//Allowed fw size in MB
#define FLASH_SIZE_MB 2
//Current compiled fw size in MB
#define FLASH_SIZE_LIMIT_MB 1
// clang-format on
