#pragma once
// DO NOT EDIT: IT IS AUTO GENERATED BY CMAKE!!!!

// clang-format off
//Allowed fw size in MB
#define FLASH_SIZE_MB 4
//Current compiled fw size in MB
#define FLASH_SIZE_LIMIT_MB 3.5
// clang-format on
