name: Check formatting

on: [pull_request]

jobs:
  check_format:
    runs-on: ubuntu-latest
    name: Check formatting
    strategy:
      matrix:
        path:
          - "firmware/common"
          - "firmware/application"
          - "firmware/baseband"
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format-18
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-18

      - name: clang-format check
        run: |
          set -euo pipefail
          clang-format-18 --version
          ROOT="${{ matrix.path }}"
          find "$ROOT" -type f \( \
              -name '*.c' -o -name '*.cpp' -o \
              -name '*.h' -o -name '*.hpp' \
            \) -print0 \
            | xargs -0 -r clang-format-18 --dry-run --Werror --style=file --fallback-style=Chromium
